### ISSUE TITLE
Crash on startup with disabled network: No such host is known

### ISSUE THREAD

**Issue by cweiske** [berrnd/FritzBoxCallMonitor#1]
When the computer's network connection is disabled and FritzBoxCallMonitor is started, it crashes immediately:
> FritzBoxCallMonitor has stopped working

The terminal in the background says:
```
Unhandled Exception: System.Net.Sockets.SocketException: No such host is known
   at System.Net.Dns.GetAddrInfo(String name)
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at FritzBoxCallMonitor.Program.Main()
```

It would be nice if FBCM would not crash but wait until the network interface gets connected and then tries to connect to the Fritzbox.

(This is on Windows 7 when disabling the network interface in the network connection adapter settings)

**Comment by berrnd** [comment]
The used "EventDrivenTcpClient" already handles auto reconnecting. So basically this most likely already works - when using the IP address of your FritzBox instead. The mentioned error is clearly a DNS lookup error.

However, this tool naturally and obviously requires a enabled and active network connection, so the simplest way to workaround that would be to just plug in your cable before starting it - or whatever the practical problem here is.

**Comment by cweiske** [comment]
Thank you for the hint about using the IP address. When doing that, it does indeed work and connect automatically within ~10 seconds when the network adapter is enabled:

```
Program OnOutgoingCall = OnOutgoingCall.bat
Program OnIncomingCall = OnIncomingCall.bat
Program OnConnected = OnConnected.bat
Program OnConnectionEnd = OnConnectionEnd.bat
Connection status changed: Connecting
Connection status changed: ConnectFail_Timeout
Connection status changed: DisconnectedByHost
Connection status changed: AutoReconnecting
Connection status changed: Connecting
Connection status changed: Connected
```

The practical problem here is that the FBCM shall start automatically in the background, and I wanted to see what happens in edge cases (router temporarily not available when PC starts up).
